## This content is duplicated here from configs/config_designers.yml because I'm building this site through Github Pages, and Github Pages just looks for the _config.yml file in the root directory to create the build.
# project definitions
project: doc
audience: designers
product: all
platform: all
version: all
destination: ../doc_designers
topnav_title: Jekyll Documentation Theme
homepage_title: Jekyll Documentation Theme &mdash; Designers
site_title: Jekyll Documentation Theme &mdash; Designers
disqus_shortname: idrbwjekyll
google_analytics: UA-66296557-1

# variables

sidebar_tagline: designers
sidebar_version: version 3.0

port: 4001

exclude:
  - doc_writer*
  - configs/
  - _site
  - di_multi*

# same for all
host: 127.0.0.1
feedback_email: tomjohnson1492@gmail.com
sidebar_accordion: true
markdown: redcarpet
print: false
theme_file: theme-blue.css
# only use suffix if you need to force index.html to display
# suffix: index.html

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

highlighter: pygments

collections:
  tooltips:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true