# Site settings
title: Jekyll-doc # your project's title
contact_email: tomjohnson1492@gmail.com # a contact email for the project
description: > # a description of your project. the ">" means to ignore newlines until "baseurl:"  
  A theme based on Jekyll designed for technical writers creating help systems. Feel free to clone, fork, and otherwise use. It's all open source and free to implement. 
  Please consider contributing back any innovations you make so that others can benefit.
baseurl: "/jekyll-doc" # the subpath of your site. If you're publishing to the root directory, just type "". Usually set this as your project name.
url: "http://tomjohnson1492.github.io" # the base hostname & protocol for your site
host: 127.0.0.1 # specified here because 0.0.0 gets defaulted to search in Chrome. this is how you will preview the site.
port: 4000 # specified here in case you have multiple sites and want to view them simultaneously (you'll need different ports)


## single sourcing toggles: here you set some variables that will be used as toggles for single sourcing projects. If you just have one site, you can probably ignore these two fields. 
# But the theme is designed to generate multiple outputs from the same theme -- this is the paradigm of single sourcing that is common to the tech writer's world but which isn't so
# common in the Jekyll world.

# hi my name is tom.


project: jekyll-doc # add your project name here
data_source: projects/jekyll-doc/data
plugins: projects/jekyll-doc/plugins
layouts: projects/jekyll-doc/layouts
destination: projects/jekyll-doc/site_builds
homepage_title: Jekyll-doc theme
homepage_id: jekyll-doc-homepage

## build settings -- leave as us

markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments

exclude: # put all files or directories that you want to exclude from your project here.
  - "Gemfile"
  - "Gemfile.lock"
  - _drafts
  - projects/jekyll-doc/site_builds


# these are defaults that get applied to each page or post. you don't have to set these settings in the frontmatter if you put them here. But frontmatter settings will override the configs here.
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: include
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: include

sass:
    sass_dir: _sass

