permalink: /:year/:month/:day/:title/
# this sets the style for permalinks. The date formatting (/:year/:month/:day/) will only apply to blog posts, while the pages will just show the title.
url: http://idratherbewriting.com
# where you plan to publish your site
baseurl: "/documentation-theme-jekyll"
# any subdirectory that appears after the domain where you're publishing your site
output: web
# this property is useful for conditional filtering of content that is separate from the PDF.
topnav_title: Jekyll Documentation Theme
# this appears on the top navigation bar next to the home button
site_title: Jekyll theme for designers
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)
company_name: Your company
# this appears in the footer
github_editme_path: tomjohnson1492/documentation-theme-jekyll/edit/reviews
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.
disqus_shortname: idrbwjekyll
# if you're using disqus for comments, add the shortname here. if not, leave this value blank.
host: 127.0.0.1
# the preview server used. Leave as is.
port: 4005
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts.

exclude:
  - _site
  - _drafts/
  - .idea/
# these are the files and directories that jekyll will exclude from the build

feedback_email: tomjohnson1492@gmail.com
# used as a contact email for the Feedback link in the top navigation bar

#feedback_disable: true
#feedback_text: "Need help?"
#feedback_link: "http://helpy.io/"
# change feedback link behaviour if you use a support ticketing system or something else

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

collections:
  tooltips:
    output: false
# collection declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output.

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: home_sidebar
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
      sidebar: tags_sidebar

# these are defaults used for the frontmatter for these file types


description: "Intended as a documentation theme based on Jekyll for technical writers documenting software and other technical products, this theme has all the elements you would need to handle multiple products with both multi-level sidebar navigation, tags, and other documentation features."
# the description is used in the feed.xml file