project: documentation-theme-jekyll-designer

audience: designer

product: all

platform: all

version: all

topnav_title: Jekyll for Designers

topnav_version: 2.1

tagline: Guide for designers

baseurl: "/documentation-theme-jekyll/designer"

port: 4006

host: 127.0.0.1 

url: "http://tomjohnson1492.github.io"

feedback_email: tomjohnson1492@gmail.com

sidebar_accordion: true

disqus_shortname: idrbwjekyll

google_analytics:  UA-408430-5

markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

highlighter: pygments

print: false

floating_nav: true

# suffix: index.html

exclude: 
  - _drafts
  - bower_components
  - .idea 
  - _site

permalink: :title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      tooltip: true
      search: true

sass:
    sass_dir: _sass

collections:
  tooltips:
    output: true