# Site settings
title: Blank Project # your project's title
contact_email: tomjohnson1492@gmail.com # a contact email for the project
description: > # a description of your project. the ">" means to ignore newlines until "baseurl:"  
  Here is a description of the project. 
baseurl: "/blankproject" # the subpath of your site. If you're publishing to the root directory, just type "". Usually set this as your project name.
url: "http://yourwebsiteurl.com" # the base hostname & protocol for your site
host: 127.0.0.1 # specified here because 0.0.0 gets defaulted to search in Chrome. this is how you will preview the site.
port: 4001 # specified here in case you have multiple sites and want to view them simultaneously (you'll need different ports)


## single sourcing toggles: here you set some variables that will be used as toggles for single sourcing projects. If you just have one site, you can probably ignore these two fields. 
# But the theme is designed to generate multiple outputs from the same theme -- this is the paradigm of single sourcing that is common to the tech writer's world but which isn't so
# common in the Jekyll world.


project: blankproject # add your project name here
data_source: projects/blankproject/data
plugins: projects/blankproject/plugins
layouts: projects/blankproject/layouts
includes_directory: blankproject # the includes directory is the only directory not contained within projects (due to technical limitations)

destination: projects/blankproject/site_builds
homepage_title: blankproject theme
homepage_id: blankproject-homepage
footer_id: blankproject-footer

disqus_shortname:  #example: idrbwjekyll if you leave this blank,  disqus is not run. if you want to run it, add your code here.
# for basicproject, the shortname is basicproject
google_analytics:  #example: UA-908430-5. f you leave this field blank, google analytics is not run.
css_stylesheet: blankproject/styles/projectstyles.css 
js_source: blankproject/scripts/projectscripts.js



## build settings -- leave as is

markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments

exclude: # put all files or directories that you want to exclude from your project here.
  - "Gemfile"
  - "Gemfile.lock"
  - _drafts
  - projects/blankproject/site_builds


# these are defaults that get applied to each page or post. you don't have to set these settings in the frontmatter if you put them here. But frontmatter settings will override the configs here.
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: include
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: include

sass:
    sass_dir: _sass

# used for translation 
search_placeholder_text: search...
search_no_results_text: No results found.

