# project definitions
project: doc_writers
audience: writers
product: all
platform: all
version: all
destination: ../doc_writers
topnav_title: Jekyll Documentation Theme
homepage_title: Jekyll Documentation Theme &mdash; Writers
site_title: Jekyll Documentation Theme &mdash; Writers
disqus_shortname: idrbwjekyll
google_analytics: UA-66296557-1
github_editme_path: tomjohnson1492/documentation-theme-jekyll/blob/gh-pages
# don't use a slash before or after the above path. here's how this url gets written out in page.html: https://github.com/{{site.github_editme_path}}{{page.url | replace: '.html', '.md'}}

# variables

sidebar_tagline: writers
sidebar_version: version 3.0
theme_file: theme-green.css
project_file_name: doc

port: 4003
exclude:
  - doc_designers*
  - configs/
  - _site
  - _drafts
  - di_multi*

# same for all
host: 127.0.0.1
feedback_email: tomjohnson1492@gmail.com
sidebar_accordion: true
markdown: redcarpet
print: false

# only use suffix if you need to force index.html to display
# suffix: index.html

highlighter: pygments

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

collections:
  tooltips:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true


